---
# tasks file for adoptopenjdk8_hotspot

# install AdoptOpenJDK HotSpot 1.8
- name: download AdoptOpenJDK HotSpot 1.8
  get_url:
    url: "{{ site_url }}//jdk{{ jdk_version }}-b03/OpenJDK8U-jdk_x64_linux_hotspot_{{ jdk_version }}b03.tar.gz"
    dest: "/tmp/OpenJDK8U-jdk_x64_linux_hotspot_{{ jdk_version }}b03.tar.gz"
    mode: 0644
    checksum: "sha256:{{ site_url }}/jdk{{ jdk_version }}-b03/OpenJDK8U-jdk_x64_linux_hotspot_{{ jdk_version }}b03.tar.gz.sha256.txt"

- name: make directory for JDK
  file: path=/opt/java state=directory mode=0775

- name: unarchive JDK
  unarchive:
    src: "/tmp/OpenJDK8U-jdk_x64_linux_hotspot_{{ jdk_version }}b03.tar.gz"
    dest: /opt/java
    copy: no

- name: make symbolic links for JDK
  file: src="/opt/java/jdk{{ jdk_version }}-b03" dest='/opt/java/current' state=link

- name: be sure enviroment valiable is configured
  template: src=java.sh.j2 dest=/etc/profile.d/java.sh